name: Process Config

on:
  #schedule:
  #  - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  process-config:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Post checkuot setup
        run: |
          git config --global --add safe.directory `pwd`
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase

      - name: Set up environment
        run: |
          mkdir -p processed_config
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Process Config
        run: |
          bash ./process_config.sh

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Push updated package list database"
          git pull --rebase
          git push
